### ISSUE TITLE
A bit messy getting working with an existing Lacinia-pedestal setup

### ISSUE THREAD

**Issue by tolgraven** [WorksHub/leona#38] opened 2019-09-25 15:00 UTC
Threw me off a bunch of times and the setup is definitely common. I blindly assumed using their format would mean i'd all play nice, and it does, so it's more about documentation really - figuring out the order of things took a while, then idiosyncrasies like your final compile and theirs being different layouts, and the wrong kinda pipeline easily leading to errors being swallowed before reaching you, lots of confusion.

**Comment by acron0** [comment] 2019-09-30 08:59
Hi @tolgraven , we are definitely interested in improving the onboarding experience and documentation. If there are legitimate changes you feel would be beneficial then I encourage you to put them in a PR so we can discuss. Alternatively we are in #workshub on Clojurians Slack.

**Comment by acron0** [comment] 2019-10-09 08:50
Closing this because the issue isn't super clear about what needs to change. Parity with Lacinia isn't really a design goal at this stage.

**Closed by acron0** 2019-10-09 08:50 UTC
